=== AnaOstio/SEW-XML/Ejercicio-1/Tarea-4/atributos.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/atributos" elementFormDefault="qualified" targetNamespace="http://tempuri.org/atributos" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="persona">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="datos" />
        <xs:sequence minOccurs="0" maxOccurs="1">
          <xs:element ref="persona" />
          <xs:element ref="persona" />
          <xs:element ref="persona" />
        </xs:sequence>
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required" />
      <xs:attribute name="apellidos" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="datos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nacimiento" />
        <xs:element ref="residencia" />
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="foto" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="video" />
        <xs:element ref="comentario" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nacimiento">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="lugar" />
        <xs:element ref="fecha" />
        <xs:element ref="coord" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="residencia">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="lugar" />
        <xs:element ref="coord" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="foto" type="xs:string" />
  <xs:element name="video" type="xs:string" />
  <xs:element name="comentario" type="xs:string" />
  <xs:element name="lugar" type="xs:string" />
  <xs:element name="fecha" type="xs:string" />
  <xs:element name="coord">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="latitud" />
        <xs:element ref="longitud" />
        <xs:element ref="altitud" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="longitud" type="xs:string" />
  <xs:element name="latitud" type="xs:string" />
  <xs:element name="altitud" type="xs:string" />
</xs:schema>

=== AnaOstio/SEW-XML/Ejercicio-1/Tarea-5/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
	<persona nombre = "Ana" apellidos = "Fernández Ostio" xmlns="http://tempuri.org/atributos"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tempuri.org/atributos atributos.xsd">
		<datos>
			<nacimiento>
				<lugar>Hospital del Naranco, Oviedo</lugar>
				<fecha>2001-12-30</fecha>
				
				<coord>
					<latitud>43.369722</latitud>
					<longitud>-5.872797</longitud>
					<altitud>120</altitud>
				</coord>
			</nacimiento>
			
			<residencia>
				<lugar>La Felguera, Langreo</lugar>
				<coord>
					<latitud>43.300599</latitud>
					<longitud>-5.686115</longitud>
					<altitud>120</altitud>
				</coord>
			</residencia>
			
			<foto>multimedia/img/yo.png</foto>
			<video>multimedia/video/yo.mp4</video>
			<comentario>Estudiante del grado de informatica del software</comentario>
		</datos>
		<persona nombre = "Andrea" apellidos = "Romero Fernández">
			<datos>
				<nacimiento>
					<lugar>Hospital Valle del Nalón, Langreo</lugar>
					<fecha>2001-06-23</fecha>
					<coord>
						<latitud>43.327384</latitud>
						<longitud>-5.721423</longitud>
						<altitud>120</altitud>
					</coord>
				</nacimiento>
				
				<residencia>
					<lugar>La Felguera, Langreo</lugar>
					<coord>
						<latitud>43.313460</latitud>
						<longitud>-5.684037</longitud>
						<altitud>140</altitud>
					</coord>
				</residencia>
				
				<foto>multimedia/img/andrea.png</foto>
				<comentario>Puede pasarse horas en tiktok</comentario>
			</datos>
			
			<persona nombre = "Sara" apellidos = "Rodríguez Gonzalez">
				<datos>
					<nacimiento>
						<lugar>Hospital Valle del Nalón, Langreo</lugar>
						<fecha>2001-06-23</fecha>
						<coord>
							<latitud>43.328808</latitud>
							<longitud>-5.722335</longitud>
							<altitud>120</altitud>
						</coord>
					</nacimiento>
					
					<residencia>
						<lugar>La Felguera, Langreo</lugar>
						<coord>
							<latitud>43.307858</latitud>
							<longitud>-5.694365</longitud>
							<altitud>140</altitud>
						</coord>
					</residencia>
					
					<foto>multimedia/img/sara.png</foto>
					<comentario>Estudia fuera de Asturias</comentario>
				</datos>
			
			</persona> 
			
			<persona nombre = "Sofía" apellidos = "Nevado Domínguez">
				<datos>
					<nacimiento>
						<lugar>Hospital Universitario de Asturias, Oviedo</lugar>
						<fecha>2001-01-27</fecha>
						<coord>
							<latitud>43.374761</latitud>
							<longitud>-5.828411</longitud>
							<altitud>120</altitud>
						</coord>
					</nacimiento>
					
					<residencia>
						<lugar>La Felguera, Langreo</lugar>
						<coord>
							<latitud>43.310724</latitud>
							<longitud>-5.696117s</longitud>
							<altitud>140</altitud>
						</coord>
					</residencia>
					
					<foto>multimedia/img/sofia.png</foto>
					<video>multimedia/video/sofia.mp4</video>
					<video>multimedia/video/sofia2.mp4</video>
					<video>multimedia/video/sofia3.mp4</video>
					<comentario>Toca el violin y el piano, además tambien canta</comentario>
				</datos>
			
			</persona> 
			
			<persona nombre = "Carlos" apellidos = "Aparicio Rodríguez">
				<datos>
					<nacimiento>
						<lugar>Hospital Cabueñes, Gijón</lugar>
						<fecha>2001-04-03</fecha>
						<coord>
							<latitud>43.525430</latitud>
							<longitud>-5.606915</longitud>
							<altitud>120</altitud>
						</coord>
					</nacimiento>
					
					<residencia>
						<lugar>La Felguera, Langreo</lugar>
						<coord>
							<latitud>43.308383</latitud>
							<longitud>-5.694912</longitud>
							<altitud>140</altitud>
						</coord>
					</residencia>
					
					<foto>multimedia/img/carlos.png</foto>
					<video>mutimedia/video/carlos.mp4</video>
					<comentario>No se le ve ni el pelo, está siemrpe en la montaña</comentario>
				</datos>
		
			</persona> 
			
		</persona> 
		
		<persona nombre = "Sonia" apellidos = "Fernández Coto">
			<datos>
				<nacimiento>
					<lugar>Hospital del Naranco, Oviedo</lugar>
					<fecha>2001-07-18</fecha>
					<coord>
						<latitud>43.370522</latitud>
						<longitud>-5.873290</longitud>
						<altitud>120</altitud>
					</coord>
				</nacimiento>
				
				<residencia>
					<lugar>Villoria, Laviana</lugar>
					<coord>
						<latitud>43.217147</latitud>
						<longitud>-5.563205</longitud>
						<altitud>120</altitud>
					</coord>
				</residencia>
				
				<foto>multimedia/img/sonia.png</foto>
				<video>multimedia/video/sonia.mp4</video>
				<video>multimedia/video/sonia2.mp4</video>
				<comentario>Que guapa va esta chica siempre</comentario>
			</datos>
			
			<persona nombre = "Alicia" apellidos = "Fernández Pushkina">
				<datos>
					<nacimiento>
						<lugar>Hospital Álvarez Buylla, Mieres</lugar>
						<fecha>2001-02-17</fecha>
						<coord>
							<latitud>43.226214</latitud>
							<longitud>-5.780912</longitud>
							<altitud>120</altitud>
						</coord>
					</nacimiento>
					
					<residencia>
						<lugar>Mieres</lugar>
						<coord>
							<latitud>43.254424</latitud>
							<longitud>-5.780472</longitud>
							<altitud>120</altitud>
						</coord>
					</residencia>
					
					<foto>multimedia/img/alicia.png</foto>
					<video>multimedia/video/ali.mp4</video>
					<comentario>Dibuja muy bien y además tiene unas mascotas muy monas</comentario>
				</datos>
				
			</persona> 
			
			<persona nombre = "Miriam" apellidos = "Gonzalez Alonso">
				<datos>
					<nacimiento>
						<lugar>Hospital del Naranco, Oviedo</lugar>
						<fecha>2001-05-23</fecha>
						<coord>
							<latitud>43.550294</latitud>
							<longitud> -5.699638</longitud>
							<altitud>120</altitud>
						</coord>
					</nacimiento>
					
					<residencia>
						<lugar>Oviedo</lugar>
						<coord>
							<latitud>43.370756</latitud>
							<longitud>-5.854382</longitud>
							<altitud>120</altitud>
						</coord>
					</residencia>
					
					<foto>multimedia/img/mir.png</foto>
					<comentario>En realidad es de laviana</comentario>
				</datos>
				
			</persona> 
			
			<persona nombre = "Hector" apellidos = "Lavandeira Fernández">
				<datos>
					<nacimiento>
						<lugar>Hospital del Naranco, Oviedo</lugar>
						<fecha>2001-12-25</fecha>
						<coord>
							<latitud>43.370522</latitud>
							<longitud>-5.873290</longitud>
							<altitud>120</altitud>
						</coord>
					</nacimiento>
					
					<residencia>
						<lugar>Oviedo</lugar>
						<coord>
							<latitud>43.358549</latitud>
							<longitud>-5.840642</longitud>
							<altitud>120</altitud>
						</coord>
					</residencia>
					
					<foto>multimedia/img/hector.png</foto>
					<video>multimedia/video/hector.mp4</video>
					<comentario>capricornio de confianza</comentario>
				</datos>
				
			</persona> 
			
		</persona> 
		
		<persona nombre = "Sergio" apellidos = "Murillo Álvarez">
			<datos>
				<nacimiento>
					<lugar>Hospital del Naranco, Oviedo</lugar>
					<fecha>2001-05-23</fecha>
					<coord>
						<latitud>43.368802</latitud>
						<longitud>-5.872073</longitud>
						<altitud>120</altitud>
					</coord>
				</nacimiento>
				
				<residencia>
					<lugar>Laviana</lugar>
					<coord>
						<latitud>43.247722</latitud>
						<longitud>-5.562731</longitud>
						<altitud>120</altitud>
					</coord>
				</residencia>
				
				<foto>multimedia/img/sergio.png</foto>
				<video>multimedia/video/sergio.mp4</video>
				<comentario>Fan de hasbulla y de los Mercedes Benz</comentario>
			</datos>
			
			<persona nombre = "Sara" apellidos = "Ferrero Lopez">
				<datos>
					<nacimiento>
						<lugar>Hospital del Naranco, Oviedo</lugar>
						<fecha>2001-07-18</fecha>
						<coord>
							<latitud>43.371403</latitud>
							<longitud>-5.873267</longitud>
							<altitud>120</altitud>
						</coord>
					</nacimiento>
					
					<residencia>
						<lugar>La Felguera, Langreo</lugar>
						<coord>
							<latitud>43.30819278631577</latitud>
							<longitud>-5.694307387923418</longitud>
							<altitud>120</altitud>
						</coord>
					</residencia>
					
					<foto>multimedia/img/saraf.png</foto>
					<video>multimedia/video/saraf.mp4</video>
					<comentario>estudia en gijon pero le cuesta</comentario>
				</datos>
			</persona> 
			
			<persona nombre = "Noemí" apellidos = "Cuesta Murillo">
				<datos>
					<nacimiento>
						<lugar>Hospital Universitario de Asturias, Oviedo</lugar>
						<fecha>2001-07-06</fecha>
						<coord>
							<latitud>43.375899</latitud>
							<longitud>-5.823658</longitud>
							<altitud>120</altitud>
						</coord>
					</nacimiento>
					
					<residencia>
						<lugar>La Felguera, Langreo</lugar>
						<coord>
							<latitud>43.309329</latitud>
							<longitud>-5.695246</longitud>
							<altitud>120</altitud>
						</coord>
					</residencia>
					
					<foto>multimedia/img/noemi.png</foto>
					<comentario>vive por y para la compe</comentario>
				</datos>
			</persona> 
			<persona nombre = "Darío" apellidos = "Martínez Bajo">
				<datos>
					<nacimiento>
						<lugar>Hospital Universitario de Asturias, Oviedo</lugar>
						<fecha>2001-04-11</fecha>
						<coord>
							<latitud>43.524259</latitud>
							<longitud>-5.605899</longitud>
							<altitud>120</altitud>
						</coord>
					</nacimiento>
					
					<residencia>
						<lugar>Tuilla, Langreo</lugar>
						<coord>
							<latitud>43.328766</latitud>
							<longitud>-5.643816</longitud>
							<altitud>120</altitud>
						</coord>
					</residencia>
					
					<foto>multimedia/img/dario.png</foto>
					<video>multimedia/video/dario.mp4</video>
					<comentario>puede pasarse horas mirando en stockx</comentario>
				</datos>
			</persona> 
		</persona> 
	</persona>
