=== AnaOstio/SEW-XML/Ejercicio-1/Tarea-2/atributos.dtd
<!ELEMENT red (persona)>
<!ATTLIST persona 
    nombre CDATA  #REQUIRED
    apellidos CDATA #REQUIRED>
<!ELEMENT persona (datos, person?, persona?, persona?)>
<!ELEMENT datos (nacimiento, residencia, foto+, video+, comentario)>
<!ELEMENT comentario (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT nacimiento (lugar, fecha, coord)> 
<!ELEMENT residencia (lugar, coord)> 
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT coord (longitud, latitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

=== AnaOstio/SEW-XML/Ejercicio-1/Tarea-2/red-social.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE red SYSTEM "atributos.dtd">
<red>
    <persona nombre = "Ana" apellidos = "Fernández Ostio">
        <datos>
            <nacimiento>
                <lugar>Hospital Monte Naranco, Oviedo</lugar>
                <fecha>2001-12-30</fecha>
                <coord>
                    <longitud>2,4</longitud>
                    <altitud>4,5</altitud>
                    <latitud>2,9</latitud>
                </coord>
            </nacimiento>
            <residencia>
                <lugar>La Felguera</lugar>
                <coord>
                    <longitud>12</longitud>
                    <altitud>89</altitud>
                    <latitud>23</latitud>
                </coord>
            </residencia>
            <foto>img/hola.png</foto>
            <video>videos/lol.mp4</video>
            <comentario>Estudiante de la asignatura SEW</comentario>
        </datos>
        <persona nombre = "Andrea" apellidos = "Romero Fernández">
            <datos>
                <nacimiento>
                    <lugar>Hospital Monte Naranco, Oviedo</lugar>
                    <fecha>2001-06-23</fecha>
                    <coord>
                        <longitud>2,4</longitud>
                        <altitud>4,5</altitud>
                        <latitud>2,9</latitud>
                    </coord>
                </nacimiento>
                <residencia>
                    <lugar>La Felguera</lugar>
                    <coord>
                        <longitud>12</longitud>
                        <altitud>89</altitud>
                        <latitud>23</latitud>
                    </coord>
                </residencia>
                <foto>img/andrea.png</foto>
                <video>videos/lol.mp4</video>
                <comentario>Estudiante de magisterio.</comentario>
            </datos>
        </persona>
        <persona nombre = "Sonia" apellidos = "Fernández Coto">
            <datos>
                <nacimiento>
                    <lugar>Hospital Monte Naranco, Oviedo</lugar>
                    <fecha>2001-12-30</fecha>
                    <coord>
                        <longitud>2,4</longitud>
                        <altitud>4,5</altitud>
                        <latitud>2,9</latitud>
                    </coord>
                </nacimiento>
                <residencia>
                    <lugar>Villoria</lugar>
                    <coord>
                        <longitud>12</longitud>
                        <altitud>89</altitud>
                        <latitud>23</latitud>
                    </coord>
                </residencia>
                <foto>img/sonia.png</foto>
                <comentario>Estudiante de la asignatura SEW</comentario>
            </datos>
        </persona>
        <persona nombre = "Sergio" apellidos = "Murillo Álvarez">
            <datos>
                <nacimiento>
                    <lugar>Hospital Monte Naranco, Oviedo</lugar>
                    <fecha>2001-05-23</fecha>
                    <coord>
                        <longitud>2,4</longitud>
                        <altitud>4,5</altitud>
                        <latitud>2,9</latitud>
                    </coord>
                </nacimiento>
                <residencia>
                    <lugar>Laviana</lugar>
                    <coord>
                        <longitud>12</longitud>
                        <altitud>89</altitud>
                        <latitud>23</latitud>
                    </coord>
                </residencia>
                <foto>img/sergio.png</foto>
                <video>videos/wow.mp4</video>
                <comentario>Le encanta jugar al wow</comentario>
            </datos>
        </persona>
    </persona>
</red>
